### ISSUE TITLE
New idea

### ISSUE THREAD

**Issue by zhusuner** [GVenusLeo/MeRead#1]
增加第三方API的支持（Fever API / Google Reader API）
除列表外，增加左图右文的视图(图一)
b站视频播放尺寸bug（图二）
![Screenshot_20221128_110217](https://user-images.githubusercontent.com/80241679/204182483-6d9d4a7c-b219-4b69-917a-ea04dcbb6a90.jpg)

![Screenshot_20221128_110246](https://user-images.githubusercontent.com/80241679/204182493-907c1593-5f18-49e3-be02-485d7754c0e6.jpg)

**Comment by GVenusLeo** [comment]
感谢反馈！

1. 我主要是想做一个基于本地的 Feed 阅读器，因此暂时不考虑其他 API 的支持。
2. 左图右文的列表视图会考虑的。
3. 视频尺寸的问题我已经在 [v0.1.3](https://github.com/GVenusLeo/MeRead/releases/tag/v0.1.3) 版本中尝试修复，可以更新试一下。
