### ISSUE TITLE
添加订阅源无法展示内容

### ISSUE THREAD

**Issue by NavinChen** [gvenusleo/MeRead#23]
订阅源地址
https://www.ezindie.com/feed/rss.xml

**Comment by gvenusleo** [comment]
请具体说明「无法展示内容」是指什么？

是添加订阅源时无法解析出订阅源信息？还是添加成功后无法刷新出订阅源的内容？

**Comment by NavinChen** [comment]
> 请具体说明「无法展示内容」是指什么？
> 
> 是添加订阅源时无法解析出订阅源信息？还是添加成功后无法刷新出订阅源的内容？

老哥好，就是点击文章，只能展示标题，内容无法展示……

**Comment by gvenusleo** [comment]
我测试了一下好像没啥问题。请问方便截个图看看吗？

**Comment by NavinChen** [comment]
> 我测试了一下好像没啥问题。请问方便截个图看看吗？

右上角第二个按钮，按了一下，就可以了……谢谢老哥
