### ISSUE TITLE
手机提示有病毒哎

### ISSUE THREAD

**Issue by shexiaobin** [gvenusleo/MeRead#3]

**Comment by GVenusLeo** [comment]
啊？请问手机系统是？有具体的提示信息吗？

**Comment by kiss2u** [comment]
huawei30s
鸿蒙2.0
报毒

**Comment by GVenusLeo** [comment]
鸿蒙系统的话，这种情况比较常见了。华为对第三方包的检测非常严格，不是从应用市场下载的软件好多都会被提示有「病毒」🙃

可以关闭华为的「纯净模式」看看 ~

**Comment by shexiaobin** [comment]
我是vivo

**Comment by gvenusleo** [comment]
> 我是vivo

卸载原来的版本，安装最新的 v0.4.0 版本看看呢？

**Comment by shexiaobin** [comment]
现在可以了，没有提示病毒，能不能添加feedly数据源呢

**Comment by gvenusleo** [comment]
> 现在可以了，没有提示病毒，能不能添加feedly数据源呢

暂时不考虑支持其他 RSS 阅读器的 API，订阅源的迁移推荐使用 OPML 的导出与导入。
